kind: Service
apiVersion: v1
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  ports: 
    - port: 80
  selector:
    app: demoapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp
spec:
  rules:
    - host: demoapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoapp
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
      - name: demoapp
        image: ghcr.io/discapes/k8s-example:master
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: redis-master 
          # cannot write to replica
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: redis-password
        ports:
        - containerPort: 80
