kind: Service
apiVersion: v1
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  ports: - port: 80
  selector:
    app: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
      - name: demoapp
        image: ghcr.io/discapes/k8s-example:master
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: redis-master 
          # can't write to replica
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: redis-password
        ports:
        - containerPort: 80
